var elements = [
    ["Hydrogen", 1, "H", 1.008, "Hydrogen is the most abundant chemical substance in the universe, constituting roughly 75% of all baryonic mass. Non-remnant stars are mainly composed of hydrogen in the plasma state. The most common isotope of hydrogen, termed protium (name rarely used, symbol 1H), has one proton and no neutrons."],
    ["Helium", 2, "He", 4.003, "It is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas, the first in the noble gas group in the periodic table. Its boiling point is the lowest among all the elements. Helium is the second lightest and second most abundant element in the observable universe (hydrogen is the lightest and most abundant). It is present at about 24% of the total elemental mass, which is more than 12 times the mass of all the heavier elements combined."],
    ["Lithium", 3, "Li", 6.941, "Lithium is the lightest metal and the lightest solid element. Like all alkali metals, lithium is highly reactive and flammable, and must be stored in mineral oil. When cut, it exhibits a metallic luster, but moist air corrodes it quickly to a dull silvery gray, then black tarnish. It never occurs freely in nature, but only in (usually ionic) compounds, such as pegmatitic minerals, which were once the main source of lithium. Due to its solubility as an ion, it is present in ocean water and is commonly obtained from brines."],
    ["Beryllium", 4, "Be", 9.012, "Beryllium is a relatively rare element in the universe, usually occurring as a product of the spallation of larger atomic nuclei that have collided with cosmic rays. Within the cores of stars, beryllium is depleted as it is fused into heavier elements. It is a divalent element which occurs naturally only in combination with other elements in minerals. Notable gemstones which contain beryllium include beryl (aquamarine, emerald) and chrysoberyl. As a free element it is a steel-gray, strong, lightweight and brittle alkaline earth metal."],
    ["Boron", 5, "B", 10.811, "Boron is produced entirely by cosmic ray spallation and supernovae and not by stellar nucleosynthesis, it is a low-abundance element in the Solar System and in the Earth's crust. It constitutes about 0.001 percent by weight of Earth's crust. Boron is concentrated on Earth by the water-solubility of its more common naturally occurring compounds, the borate minerals. These are mined industrially as evaporites, such as borax and kernite. The largest known boron deposits are in Turkey, the largest producer of boron minerals."],
    ["Carbon", 6, "C", 12.011, "Carbon is nonmetallic and tetravalent—making four electrons available to form covalent chemical bonds. It belongs to group 14 of the periodic table. Carbon makes up only about 0.025 percent of Earth's crust. Three isotopes occur naturally, 12C and 13C being stable, while 14C is a radionuclide, decaying with a half-life of about 5,730 years. Carbon is one of the few elements known since antiquity."],
    ["Nitrogen", 7, "N", 14.007, "Nitrogen was first discovered and isolated by Scottish physician Daniel Rutherford in 1772. Although Carl Wilhelm Scheele and Henry Cavendish had independently done so at about the same time, Rutherford is generally accorded the credit because his work was published first. The name nitrogène was suggested by French chemist Jean-Antoine-Claude Chaptal in 1790 when it was found that nitrogen was present in nitric acid and nitrates."],
    ["Oxygen", 8, "O", 15.999, "Oxygen is a member of the chalcogen group, a highly reactive nonmetal, and an oxidizing agent that readily forms oxides with most elements as well as with other compounds. After hydrogen and helium, oxygen is the third-most abundant element in the universe by mass. At standard temperature and pressure, two atoms of the element bind to form dioxygen, a colorless and odorless diatomic gas with the formula O2. Diatomic oxygen gas constitutes 20.95% of the Earth's atmosphere. Oxygen makes up almost half of the Earth's crust in the form of oxides."],
    ["Fluorine", 9, "F", 18.998, "Fluorine is the lightest halogen and exists as a highly toxic pale yellow diatomic gas at standard conditions. As the most electronegative element, it is extremely reactive, as it reacts with all other elements, except for argon, neon, and helium."],
    ["Neon", 10, "Ne", 20.180, "Neon is a colorless, odorless, inert monatomic gas under standard conditions, with about two-thirds the density of air. It was discovered (along with krypton and xenon) in 1898 as one of the three residual rare inert elements remaining in dry air, after nitrogen, oxygen, argon and carbon dioxide were removed. Neon was the second of these three rare gases to be discovered and was immediately recognized as a new element from its bright red emission spectrum. Neon is chemically inert, and no uncharged neon compounds are known."],
    ["Sodium", 11, "Na", 22.990, "Sodium is a soft, silvery-white, highly reactive metal. Its only stable isotope is 23Na. The free metal does not occur in nature, and must be prepared from compounds. Sodium is the sixth most abundant element in the Earth's crust and exists in numerous minerals such as feldspars, sodalite, and rock salt (NaCl). Many salts of sodium are highly water-soluble: sodium ions have been leached by the action of water from the Earth's minerals over eons, and thus sodium and chlorine are the most common dissolved elements by weight in the oceans."],
    ["Magnesium", 12, "Mg", 24.305, "Magnesium is a shiny gray solid which bears a close physical resemblance to the other five elements in the second column of the periodic table: all group 2 elements have the same electron configuration in the outer electron shell and a similar crystal structure. It is the ninth most abundant element in the universe. It is the eighth most abundant element in the Earth's crust and the fourth most common element in the Earth, making up 13% of the planet's mass and a large fraction of the planet's mantle. It is the third most abundant element dissolved in seawater."],
    ["Aluminium", 13, "Al", 26.982, "Aluminium is a silvery-white, soft, non-magnetic and ductile metal in the boron group. By mass, aluminium is the most abundant metal in the Earth's crust and the third most abundant element (after oxygen and silicon). The abundance of aluminium decreases relative to other elements at greater depths into Earth's mantle and beyond. The chief ore of aluminium is bauxite. Aluminium metal is highly reactive, so native specimens are rare and limited to extreme reducing environments. Instead, it is found combined in over 270 different minerals."],
    ["Silicon", 14, "Si", 28.086, "Silicon is a hard, brittle crystalline solid with a blue-grey metallic lustre, and is a tetravalent metalloid and semiconductor. Its melting and boiling points of 1414 °C and 3265 °C respectively are the second-highest among all the metalloids and nonmetals, being only surpassed by boron. Silicon is the eighth most common element in the universe by mass, but very rarely occurs as the pure element in the Earth's crust. More than 90% of the Earth's crust is composed of silicate minerals, making silicon the second most abundant element in the Earth's crust."],
    ["Phosphorus", 15, "P", 30.974, "Elemental phosphorus exists in two major forms, white phosphorus and red phosphorus, but because it is highly reactive, phosphorus is never found as a free element on Earth. It has a concentration in the Earth's crust of about one gram per kilogram (compare copper at about 0.06 grams). In minerals, phosphorus generally occurs as phosphate."],
    ["Sulfur", 16, "S", 32.066, "Sulfur is abundant, multivalent and nonmetallic. Under normal conditions, sulfur atoms form cyclic octatomic molecules with a chemical formula S8. Elemental sulfur is a bright yellow, crystalline solid at room temperature.Sulfur is the tenth most common element by mass in the universe, and the fifth most common on Earth. Though sometimes found in pure, native form, sulfur on Earth usually occurs as sulfide and sulfate minerals."],
    ["Chlorine", 17, "Cl", 35.453, "The second-lightest of the halogens, Chlorine appears between fluorine and bromine in the periodic table and its properties are mostly intermediate between them. Chlorine is a yellow-green gas at room temperature. It is an extremely reactive element and a strong oxidising agent: among the elements, it has the highest electron affinity and the third-highest electronegativity on the Pauling scale, behind only oxygen and fluorine."],
    ["Argon", 18, "Ar", 39.948, "Argon is in group 18 of the periodic table and is a noble gas. Argon is the third-most abundant gas in the Earth's atmosphere, at 0.934% (9340 ppmv). It is more than twice as abundant as water vapor (which averages about 4000 ppmv, but varies greatly), 23 times as abundant as carbon dioxide (400 ppmv), and more than 500 times as abundant as neon (18 ppmv). Argon is the most abundant noble gas in Earth's crust, comprising 0.00015% of the crust. "],
    ["Potassium", 19, "K", 39.098, "Potassium is a silvery-white metal that is soft enough to be cut with a knife with little force. Potassium metal reacts rapidly with atmospheric oxygen to form flaky white potassium peroxide in only seconds of exposure. It was first isolated from potash, the ashes of plants, from which its name derives. In the periodic table, potassium is one of the alkali metals, all of which have a single valence electron in the outer electron shell, that is easily removed to create an ion with a positive charge – a cation, that combines with anions to form salts."],
    ["Calcium", 20, "Ca", 40.078, "Calcium is a reactive metal that forms a dark oxide-nitride layer when exposed to air. Its physical and chemical properties are most similar to its heavier homologues strontium and barium. It is the fifth most abundant element in Earth's crust and the third most abundant metal, after iron and aluminium. The most common calcium compound on Earth is calcium carbonate, found in limestone and the fossilised remnants of early sea life; gypsum, anhydrite, fluorite, and apatite are also sources of calcium."],
    ["Scandium", 21, "Sc", 44.956, "A silvery-white metallic d-block element, Scandium has historically been classified as a rare-earth element, together with yttrium and the lanthanides. It was discovered in 1879 by spectral analysis of the minerals euxenite and gadolinite from Scandinavia. "],
    ["Titanium", 22, "Ti", 47.867, "Titanium is a lustrous transition metal with a silver color, low density, and high strength. It is resistant to corrosion in sea water, aqua regia, and chlorine. Titanium was discovered in Cornwall, Great Britain, by William Gregor in 1791 and was named by Martin Heinrich Klaproth after the Titans of Greek mythology. The element occurs within a number of mineral deposits, principally rutile and ilmenite, which are widely distributed in the Earth's crust and lithosphere; it is found in almost all living things, as well as bodies of water, rocks, and soils."],
    ["Vanadium", 23, "V", 50.942, "Vanadium is a hard, silvery-grey, malleable transition metal. The elemental metal is rarely found in nature, but once isolated artificially, the formation of an oxide layer (passivation) somewhat stabilizes the free metal against further oxidation.Andrés Manuel del Río discovered compounds of vanadium in 1801 in Mexico by analyzing a new lead-bearing mineral he called 'brown lead'."],
    ["Chromium", 24, "Cr", 51.996, "It is the first element in group 6. It is a steely-grey, lustrous, hard and brittle transition metal. Chromium is the main additive in stainless steel, to which it adds anti-corrosive properties. Chromium is also highly valued as a metal that is able to be highly polished while resisting tarnishing. Polished chromium reflects almost 70% of the visible spectrum, with almost 90% of infrared light being reflected. The name of the element is derived from the Greek word χρῶμα, chrōma, meaning color, because many chromium compounds are intensely colored."],
    ["Manganese", 25, "Mn", 54.938, "Manganese is not found as a free element in nature; it is often found in minerals in combination with iron. Manganese is a transition metal with a multifaceted array of industrial alloy uses, particularly in stainless steels.Historically, manganese is named for pyrolusite and other black minerals from the region of Magnesia in Greece, which also gave its name to magnesium and the iron ore magnetite. By the mid-18th century, Swedish- German chemist Carl Wilhelm Scheele had used pyrolusite to produce chlorine."],
    ["Iron", 26, "Fe", 55.845, "Iron is a metal that belongs to the first transition series and group 8 of the periodic table. It is by mass the most common element on Earth, right in front of oxygen, forming much of Earth's outer and inner core. It is the fourth most common element in the Earth's crust. Iron ores, by contrast, are among the most abundant in the Earth's crust, although extracting usable metal from them requires kilns or furnaces capable of reaching 1,500 °C (2,730 °F) or higher, about 500 °C (900 °F) higher than that required to smelt copper."],
    ["Cobalt", 27, "Co", 58.933, "Like nickel, cobalt is found in the Earth's crust only in chemically combined form, save for small deposits found in alloys of natural meteoric iron. The free element, produced by reductive smelting, is a hard, lustrous, silver-gray metal.Cobalt-based blue pigments (cobalt blue) have been used since ancient times for jewelry and paints, and to impart a distinctive blue tint to glass, but the color was later thought to be due to the known metal bismuth."],
    ["Nickel", 28, "Ni", 58.693, "Nickel is a silvery-white lustrous metal with a slight golden tinge. It belongs to the transition metals and is hard and ductile. Pure nickel, powdered to maximize the reactive surface area, shows a significant chemical activity, but larger pieces are slow to react with air under standard conditions because an oxide layer forms on the surface and prevents further corrosion."],
    ["Copper", 29, "Cu", 63.546, "Copper is a soft, malleable, and ductile metal with very high thermal and electrical conductivity. A freshly exposed surface of pure copper has a pinkish-orange color. Copper is used as a conductor of heat and electricity, as a building material, and as a constituent of various metal alloys, such as sterling silver used in jewelry, cupronickel used to make marine hardware and coins, and constantan used in strain gauges and thermocouples for temperature measurement. "],
    ["Zinc", 30, "Zn", 65.38, "Zinc is a slightly brittle metal at room temperature and has a blue-silvery appearance when oxidation is removed. It is the first element in group 12 of the periodic table. In some respects, zinc is chemically similar to magnesium: both elements exhibit only one normal oxidation state (+2), and the Zn2+ and Mg2+ ions are of similar size. Zinc is the 24th most abundant element in Earth's crust and has five stable isotopes. The most common zinc ore is sphalerite (zinc blende), a zinc sulfide mineral."],
    ["Gallium", 31, "Ga", 69.723, "Elemental gallium is a soft, silvery metal at standard temperature and pressure; however in its liquid state it becomes silvery white. If too much force is applied, the gallium may fracture conchoidally. Gallium does not occur as a free element in nature, but as gallium(III) compounds in trace amounts in zinc ores and in bauxite. Elemental gallium is a liquid at temperatures greater than 29.76 °C (85.57 °F), and will melt in a person's hands at normal human body temperature of 37.0 °C (98.6 °F)."],
    ["Germanium", 32, "Ge", 72.631, "Germanium is a lustrous, hard-brittle, grayish-white metalloid in the carbon group, chemically similar to its group neighbours silicon and tin. Pure germanium is a semiconductor with an appearance similar to elemental silicon. Like silicon, germanium naturally reacts and forms complexes with oxygen in nature."],
    ["Arsenic", 33, "As", 74.922, "Arsenic occurs in many minerals, usually in combination with sulfur and metals, but also as a pure elemental crystal. Arsenic is a metalloid. It has various allotropes, but only the gray form, which has a metallic appearance, is important to industry. The primary use of arsenic is in alloys of lead (for example, in car batteries and ammunition). Arsenic is a common n-type dopant in semiconductor electronic devices, and the optoelectronic compound gallium arsenide is the second most commonly used semiconductor after doped silicon."],
    ["Selenium", 34, "Se", 78.972, "Selenium is a nonmetal (more rarely considered a metalloid) with properties that are intermediate between the elements above and below in the periodic table, sulfur and tellurium, and also has similarities to arsenic. It rarely occurs in its elemental state or as pure ore compounds in the Earth's crust. Selenium—from Ancient Greek σελήνη (selḗnē) 'Moon' – was discovered in 1817 by Jöns Jacob Berzelius, who noted the similarity of the new element to the previously discovered tellurium (named for the Earth)."],
    ["Bromine", 35, "Br", 79.904, "Bromine is the third-lightest halogen, and is a fuming red-brown liquid at room temperature that evaporates readily to form a similarly coloured gas. Its properties are thus intermediate between those of chlorine and iodine. Isolated independently by two chemists, Carl Jacob Löwig (in 1825) and Antoine Jérôme Balard (in 1826), its name was derived from the Ancient Greek βρῶμος ('stench'), referencing its sharp and disagreeable smell."],
    ["Krypton", 36, "Kr", 84.798, "Krypton is a colorless, odorless, tasteless noble gas that occurs in trace amounts in the atmosphere and is often used with other rare gases in fluorescent lamps. With rare exceptions, krypton is chemically inert. Krypton, like the other noble gases, is used in lighting and photography."],
    ["Rubidium", 37, "Rb", 85.468, "Rubidium is a very soft, silvery-white metal in the alkali metal group. Rubidium metal shares similarities to potassium metal and caesium metal in physical appearance, softness and conductivity. Rubidium cannot be stored under atmospheric oxygen, as a highly exothermic reaction will ensue, sometimes even resulting in the metal catching fire. Rubidium is the first alkali metal in the group to have a density higher than water, so it sinks, unlike the metals above it in the group."],
    ["Strontium", 38, "Sr", 87.62, "Strontium is a soft silver-white yellowish metallic element that is highly chemically reactive. The metal forms a dark oxide layer when it is exposed to air. Strontium has physical and chemical properties similar to those of its two vertical neighbors in the periodic table, calcium and barium. It occurs naturally mainly in the minerals celestine and strontianite, and is mostly mined from these."],
    ["Yttrium", 39, "Y", 88.906, "Yttrium is a silvery-metallic transition metal chemically similar to the lanthanides and has often been classified as a 'rare-earth element'. Yttrium is almost always found in combination with lanthanide elements in rare-earth minerals, and is never found in nature as a free element. 89Y is the only stable isotope, and the only isotope found in the Earth's crust.The most important uses of yttrium are LEDs and phosphors, particularly the red phosphors in television set cathode ray tube displays."],
    ["Zirconium", 40, "Zr", 91.224, "The name zirconium is taken from the name of the mineral zircon, the most important source of zirconium. It is a lustrous, grey-white, strong transition metal that closely resembles hafnium and, to a lesser extent, titanium. Zirconium is mainly used as a refractory and opacifier, although small amounts are used as an alloying agent for its strong resistance to corrosion. Zirconium forms a variety of inorganic and organometallic compounds such as zirconium dioxide and zirconocene dichloride, respectively. Five isotopes occur naturally, three of which are stable."],
    ["Niobium", 41, "Nb", 92.906, "Niobium is a light grey, crystalline, and ductile transition metal. Pure niobium has a Mohs hardness rating similar to that of pure titanium, and it has similar ductility to iron. Niobium oxidizes in the earth's atmosphere very slowly, hence its application in jewelry as a hypoallergenic alternative to nickel. Niobium is often found in the minerals pyrochlore and columbite, hence the former name 'columbium'. Its name comes from Greek mythology, specifically Niobe, who was the daughter of Tantalus, the namesake of tantalum."],
    ["Molybdenum", 42, "Mo", 95.95, "Molybdenum does not occur naturally as a free metal on Earth; it is found only in various oxidation states in minerals. The free element, a silvery metal with a gray cast, has the sixth-highest melting point of any element. It readily forms hard, stable carbides in alloys, and for this reason most of world production of the element (about 80%) is used in steel alloys, including high-strength alloys and superalloys."],
    ["Technetium", 43, "Tc", 98.907, "Technetium is the lightest element whose isotopes are all radioactive, none of which is stable other than the fully ionized state of 97Tc. Nearly all available technetium is produced as a synthetic element. Naturally occurring technetium is a spontaneous fission product in uranium ore and thorium ore, the most common source, or the product of neutron capture in molybdenum ores. The most common naturally occurring isotope is 99Tc, in traces only."],
    ["Ruthenium", 44, "Ru", 101.07, "Ruthenium is a rare transition metal belonging to the platinum group of the periodic table. Like the other metals of the platinum group, ruthenium is inert to most other chemicals. Russian-born scientist of Baltic-German ancestry Karl Ernst Claus discovered the element in 1844 at Kazan State University and named ruthenium in honor of Ruthenia (one of Medieval Latin names for Russia).[4] Ruthenium is usually found as a minor component of platinum ores. Most ruthenium produced is used in wear-resistant electrical contacts and thick-film resistors."],
    ["Rhodium", 45, "Rh", 102.906, "Rhodium is an ultra-rare, silvery-white, hard, corrosion-resistant, and chemically inert transition metal. It is a noble metal and a member of the platinum group. It has only one naturally occurring isotope, 103Rh. Naturally occurring rhodium is usually found as free metal, as an alloy with similar metals, and rarely as a chemical compound in minerals such as bowieite and rhodplumsite. It is one of the rarest and most valuable precious metals. It is found in platinum or nickel ores together with the other members of the platinum group metals."],
    ["Palladium", 46, "Pd", 106.42, "Palladium is a rare and lustrous silvery-white metal discovered in 1803 by the English chemist William Hyde Wollaston. He named it after the asteroid Pallas, which was itself named after the epithet of the Greek goddess Athena, acquired by her when she slew Pallas. Palladium, platinum, rhodium, ruthenium, iridium and osmium form a group of elements referred to as the platinum group metals (PGMs). They have similar chemical properties, but palladium has the lowest melting point and is the least dense of them."],
    ["Silver", 47, "Ag", 107.868, "Silver is a soft, white, lustrous transition metal, it exhibits the highest electrical conductivity, thermal conductivity, and reflectivity of any metal. The metal is found in the Earth's crust in the pure, free elemental form, as an alloy with gold and other metals, and in minerals such as argentite and chlorargyrite. Most silver is produced as a byproduct of copper, gold, lead, and zinc refining. Silver has long been valued as a precious metal. Silver metal is used in many bullion coins, sometimes alongside gold."],
    ["Cadmium", 48, "Cd", 112.411, "This soft, silvery-white metal is chemically similar to the two other stable metals in group 12, zinc and mercury. Like zinc, Cadmium demonstrates oxidation state +2 in most of its compounds, and like mercury, it has a lower melting point than the transition metals in groups 3 through 11. Cadmium and its congeners in group 12 are often not considered transition metals, in that they do not have partly filled d or f electron shells in the elemental or common oxidation states. The average concentration of cadmium in Earth's crust is between 0.1 and 0.5 parts per million."],
    ["Indium", 49, "In", 114.818, "Indium is the softest metal that is not an alkali metal. It is a silvery-white metal that resembles tin in appearance. It is a post-transition metal that makes up 0.21 parts per million of the Earth's crust. Indium has a melting point higher than sodium and gallium, but lower than lithium and tin. Chemically, indium is similar to gallium and thallium, and it is largely intermediate between the two in terms of its properties. Indium was discovered in 1863 by Ferdinand Reich and Hieronymous Theodor Richter by spectroscopic methods."],
    ["Tin", 50, "Sn", 118.711, "Tin is a silvery metal that characteristically has a faint yellow hue. Tin, like indium, is soft enough to be cut without much force. When a bar of tin is bent, the so-called “tin cry” can be heard as a result of twinning in tin crystals; this trait is shared by indium, cadmium, and frozen mercury. Pure tin after solidifying keeps a mirror-like appearance similar to most metals. However, in most tin alloys (such as pewter), the metal solidifies with a dull gray color. Tin is a post-transition metal in group 14 of the periodic table of elements."],
    ["Antimony", 51, "Sb", 121.760, "Antimony is a lustrous gray metalloid, it is found in nature mainly as the sulfide mineral stibnite (Sb2S3). Antimony compounds have been known since ancient times and were powdered for use as medicine and cosmetics, often known by the Arabic name kohl. Metallic antimony was also known, but it was erroneously identified as lead upon its discovery. The earliest known description of the metal in the West was written in 1540 by Vannoccio Biringuccio."],
    ["Tellurium", 52, "Te", 127.6, "Tellurium is a brittle, mildly toxic, rare, silver-white metalloid. Tellurium is chemically related to selenium and sulfur, all three of which are chalcogens. It is occasionally found in native form as elemental crystals. Tellurium is far more common in the Universe as a whole than on Earth. The primary use of tellurium is copper (tellurium copper) and steel alloys, where it improves machinability. Applications in CdTe solar panels and cadmium telluride semiconductors also consume a considerable portion of tellurium production."],
    ["Iodine", 53, "I", 126.904, "Iodine is the heaviest of the stable halogens, it exists as a lustrous, purple-black non-metallic solid at standard conditions that melts to form a deep violet liquid at 114 degrees Celsius, and boils to a violet gas at 184 degrees Celsius. However, it sublimes easily with gentle heat, resulting in a widespread misconception even taught in some science textbooks that it does not melt. The element was discovered by the French chemist Bernard Courtois in 1811, and was named two years later by Joseph Louis Gay-Lussac, after the Greek ἰώδης 'violet-coloured'."],
    ["Xenon", 54, "Xe", 131.294, "Xenon is a colorless, dense, odorless noble gas found in Earth's atmosphere in trace amounts. Although generally unreactive, xenon can undergo a few chemical reactions such as the formation of xenon hexafluoroplatinate, the first noble gas compound to be synthesized. It is used in flash lamps and arc lamps, and as a general anesthetic."],
    ["Cesium", 55, "Cs", 132.905, "Cesium is a soft, silvery-golden alkali metal with a melting point of 28.5 °C (83.3 °F), which makes it one of only five elemental metals that are liquid at or near room temperature.  Caesium has physical and chemical properties similar to those of rubidium and potassium. The most reactive of all metals, it is pyrophoric and reacts with water even at −116 °C (−177 °F). It is the least electronegative element, with a value of 0.79 on the Pauling scale."],
    ["Barium", 56, "Ba", 137.328, "Barium is a soft, silvery alkaline earth metal. Because of its high chemical reactivity, barium is never found in nature as a free element. The most common minerals of barium are barite (now called baryte) (barium sulfate, BaSO4) and witherite (barium carbonate, BaCO3), both insoluble in water. Baric is the adjectival form of barium. Barium was identified as a new element in 1774, but not reduced to a metal until 1808 with the advent of electrolysis."],

    ["Lanthanum", 57, "La", 138.905, "Lanthanum is a soft, ductile, silvery-white metal that tarnishes slowly when exposed to air and is soft enough to be cut with a knife. It is the eponym of the lanthanide series, a group of 15 similar elements between lanthanum and lutetium in the periodic table, of which lanthanum is the first and the prototype. It is also sometimes considered the first element of the 6th-period transition metals, which would put it in group 3, although lutetium is sometimes placed in this position instead. Lanthanum is traditionally counted among the rare earth elements."],
    ["Cerium", 58, "Ce", 140.116, "Cerium is a soft, ductile and silvery-white metal that tarnishes when exposed to air, and it is soft enough to be cut with a knife. Cerium is the second element in the lanthanide series, and while it often shows the +3 oxidation state characteristic of the series, it also has a stable +4 state that does not oxidize water. It is also considered one of the rare-earth elements. Cerium has no biological role in humans and is not very toxic."],
    ["Praseodymium", 59, "Pr", 140.908, "It is the third member of the lanthanide series and is traditionally considered to be one of the rare-earth metals. Praseodymium is a soft, silvery, malleable and ductile metal, valued for its magnetic, electrical, chemical, and optical properties. It is too reactive to be found in native form, and pure praseodymium metal slowly develops a green oxide coating when exposed to air. Praseodymium always occurs naturally together with the other rare-earth metals."],
    ["Neodymium", 60, "Nd", 144.242, "Neodymium belongs to the lanthanide series and is a rare-earth element. It is a hard, slightly malleable silvery metal that quickly tarnishes in air and moisture. When oxidized, neodymium reacts quickly to produce pink, purple/blue and yellow compounds in the +2, +3 and +4 oxidation states. Neodymium was discovered in 1885 by the Austrian chemist Carl Auer von Welsbach. It is present in significant quantities in the ore minerals monazite and bastnäsite."],
    ["Promethium", 61, "Pm", 144.913, "All of Promethium's isotopes are radioactive; it is extremely rare, with only about 500–600 grams naturally occurring in Earth's crust at any given time. Promethium is one of only two radioactive elements that are followed in the periodic table by elements with stable forms, the other being technetium. Chemically, promethium is a lanthanide. Promethium shows only one stable oxidation state of +3."],
    ["Samarium", 62, "Sm", 150.36, "Samarium is a moderately hard silvery metal that slowly oxidizes in air. Being a typical member of the lanthanide series, samarium usually assumes the oxidation state +3. Compounds of samarium(II) are also known, most notably the monoxide SmO, monochalcogenides SmS, SmSe and SmTe, as well as samarium(II) iodide. The last compound is a common reducing agent in chemical synthesis. Samarium has no significant biological role but is only slightly toxic."],
    ["Europium", 63, "Eu", 151.964, "Europium is the most reactive lanthanide by far, having to be stored under an inert fluid to protect it from atmospheric oxygen or moisture. Europium is also the softest lanthanide, as it can be dented with a fingernail and easily cut with a knife. When oxidation is removed a shiny-white metal is visible. Europium was isolated in 1901 and is named after the continent of Europe. Being a typical member of the lanthanide series, europium usually assumes the oxidation state +3, but the oxidation state +2 is also common."],
    ["Gadolinium", 64, "Gd", 157.25, "Gadolinium is a silvery-white metal when oxidation is removed. It is only slightly malleable and is a ductile rare-earth element. Gadolinium reacts with atmospheric oxygen or moisture slowly to form a black coating. Gadolinium below its Curie point of 20 °C (68 °F) is ferromagnetic, with an attraction to a magnetic field higher than that of nickel. Above this temperature it is the most paramagnetic element. It is found in nature only in an oxidized form."],
    ["Terbium", 65, "Tb", 58.925, "Terbium is a silvery-white, rare earth metal that is malleable, ductile, and soft enough to be cut with a knife. The ninth member of the lanthanide series, terbium is a fairly electropositive metal that reacts with water, evolving hydrogen gas. Terbium is never found in nature as a free element, but it is contained in many minerals, including cerite, gadolinite, monazite, xenotime, and euxenite. Swedish chemist Carl Gustaf Mosander discovered terbium as a chemical element in 1843."],
    ["Dysprosium", 66, "Dy", 162.500, "Dysprosium is a rare-earth element with a metallic silver luster. Dysprosium is never found in nature as a free element, though it is found in various minerals, such as xenotime. Naturally occurring dysprosium is composed of seven isotopes, the most abundant of which is 164Dy. Dysprosium was first identified in 1886 by Paul Émile Lecoq de Boisbaudran, but it was not isolated in pure form until the development of ion-exchange techniques in the 1950s."],
    ["Holmium", 67, "Ho", 164.930, "Elemental holmium is a relatively soft and malleable silvery-white metal. It is too reactive to be found uncombined in nature, but when isolated, is relatively stable in dry air at room temperature. However, it reacts with water and corrodes readily and also burns in air when heated. Holmium was discovered through isolation by Swedish chemist Per Theodor Cleve and independently by Jacques-Louis Soret and Marc Delafontaine who observed it spectroscopically in 1878. Its oxide was first isolated from rare-earth ores by Cleve in 1878."],
    ["Erbium", 68, "Er", 167.259, "A silvery-white solid metal when artificially isolated, natural erbium is always found in chemical combination with other elements. It is a lanthanide, a rare earth element, originally found in the gadolinite mine in Ytterby in Sweden, from which it got its name. Erbium's principal uses involve its pink-colored Er3+ ions, which have optical fluorescent properties particularly useful in certain laser applications."],
    ["Thulium", 69, "Tm", 168.934, "Thulium is the thirteenth and third-last element in the lanthanide series. Like the other lanthanides, the most common oxidation state is +3, seen in its oxide, halides and other compounds; because it occurs so late in the series, however, the +2 oxidation state is also stabilized by the nearly full 4f shell that results. In aqueous solution, like compounds of other late lanthanides, soluble thulium compounds form coordination complexes with nine water molecules."],
    ["Ytterbium", 70, "Yb", 173.055, "Yttrium is the fourteenth and penultimate element in the lanthanide series, which is the basis of the relative stability of its +2 oxidation state. However, like the other lanthanides, its most common oxidation state is +3, as in its oxide, halides, and other compounds. In aqueous solution, like compounds of other late lanthanides, soluble ytterbium compounds form complexes with nine water molecules. Because of its closed-shell electron configuration, its density and melting and boiling points differ significantly from those of most other lanthanides."],
    ["Lutetium", 71, "Lu", 174.967, "Lutetium is a silvery white metal, which resists corrosion in dry air, but not in moist air. Lutetium is the last element in the lanthanide series, and it is traditionally counted among the rare earths. Lutetium is sometimes considered the first element of the 6th-period transition metals, although lanthanum is more often considered as such. Lutetium was independently discovered in 1907 by French scientist Georges Urbain, Austrian mineralogist Baron Carl Auer von Welsbach, and American chemist Charles James."],

    ["Hafnium", 72, "Hf", 178.49, "A lustrous, silvery gray, tetravalent transition metal, hafnium chemically resembles zirconium and is found in many zirconium minerals. Its existence was predicted by Dmitri Mendeleev in 1869, though it was not identified until 1923, by Coster and Hevesy, making it the last stable element to be discovered. Hafnium is named after Hafnia, the Latin name for Copenhagen, where it was discovered. Hafnium is used in filaments and electrodes."],
    ["Tantalum", 73, "Ta", 180.948, "Tantalum is a rare, hard, blue-gray, lustrous transition metal that is highly corrosion-resistant. It is part of the refractory metals group, which are widely used as minor components in alloys. The chemical inertness of tantalum makes it a valuable substance for laboratory equipment, and as a substitute for platinum. Its main use today is in tantalum capacitors in electronic equipment such as mobile phones, DVD players, video game systems and computers. Tantalum is considered a technology-critical element."],
    ["Tungsten", 74, "W", 183.84, "The name tungsten comes from the former Swedish name for the tungstate mineral scheelite, tungsten which means 'heavy stone'. Tungsten is a rare metal found naturally on Earth almost exclusively combined with other elements in chemical compounds rather than alone. It was identified as a new element in 1781 and first isolated as a metal in 1783. Its important ores include wolframite and scheelite."],
    ["Rhenium", 75, "Re", 186.207, "Rhenium is a silvery-gray, heavy, third-row transition metal in group 7 of the periodic table. With an estimated average concentration of 1 part per billion (ppb), rhenium is one of the rarest elements in the Earth's crust. Rhenium has the third-highest melting point and second-highest boiling point of any stable element at 5903 K. It resembles manganese and technetium chemically and is mainly obtained as a by-product of the extraction and refinement of molybdenum and copper ores."],
    ["Osmium", 76, "Os", 190.23, "Osmium is a hard, brittle, bluish-white transition metal in the platinum group that is found as a trace element in alloys, mostly in platinum ores. Osmium is the densest naturally occurring element, with an experimentally measured (using x-ray crystallography) density of 22.59 g/cm3. Manufacturers use its alloys with platinum, iridium, and other platinum-group metals to make fountain pen nib tipping, electrical contacts, and in other applications that require extreme durability and hardness. The element's abundance in the Earth's crust is among the rarest."],
    ["Iridium", 77, "Ir", 192.217, "A very hard, brittle, silvery-white transition metal of the platinum group, iridium is considered to be the second-densest metal (after osmium) with a density of 22.56 g/cm3 as defined by experimental X-ray crystallography. However, at room temperature and standard atmospheric pressure, iridium has been calculated to have a density of 22.65 g/cm3, 0.04 g/cm3 higher than osmium measured the same way. Still, the experimental X-ray crystallography value is considered to be the most accurate, as such iridium is considered to be the second densest element."],
    ["Platinum", 78, "Pt", 195.085, "Platinum is a dense, malleable, ductile, highly unreactive, precious, silverish-white transition metal. Its name is derived from the Spanish term platino, meaning 'little silver'. It has six naturally occurring isotopes. It is one of the rarer elements in Earth's crust, with an average abundance of approximately 5 μg/kg. It occurs in some nickel and copper ores along with some native deposits, mostly in South Africa, which accounts for 80% of the world production."],
    ["Gold", 79, "Au", 196.967, "In a pure form, Gold is a bright, slightly reddish yellow, dense, soft, malleable, and ductile metal. It is one of the least reactive chemical elements and is solid under standard conditions. Gold often occurs in free elemental (native) form, as nuggets or grains, in rocks, in veins, and in alluvial deposits. It occurs in a solid solution series with the native element silver (as electrum) and also naturally alloyed with copper and palladium. Less commonly, it occurs in minerals as gold compounds, often with tellurium (gold tellurides)."],
    ["Mercury", 80, "Hg", 200.592, "Mercury is commonly known as quicksilver and was formerly named hydrargyrum (/haɪˈdrɑːrdʒərəm/ hy-DRAR-jər-əm). A heavy, silvery d-block element, mercury is the only metallic element that is liquid at standard conditions for temperature and pressure; the only other element that is liquid under these conditions is the halogen bromine, though metals such as caesium, gallium, and rubidium melt just above room temperature. Mercury occurs in deposits throughout the world mostly as cinnabar (mercuric sulfide)."],
    ["Thallium", 81, "Tl", 204.383, "Thallium is a gray post-transition metal that is not found free in nature. When isolated, thallium resembles tin, but discolors when exposed to air. Chemists William Crookes and Claude-Auguste Lamy discovered thallium independently in 1861, in residues of sulfuric acid production. Both used the newly developed method of flame spectroscopy, in which thallium produces a notable green spectral line. Thallium, from Greek θαλλός, thallós, meaning 'a green shoot or twig', was named by Crookes. "],
    ["Lead", 82, "Pb", 207.2, "Lead is a heavy metal that is denser than most common materials. Lead is soft and malleable, and also has a relatively low melting point. When freshly cut, lead is silvery with a hint of blue; it tarnishes to a dull gray color when exposed to air. Lead has the highest atomic number of any stable element and three of its isotopes are endpoints of major nuclear decay chains of heavier elements. Lead is a relatively unreactive post-transition metal."],
    ["Bismuth", 83, "Bi", 208.980, "Bismuth is a pentavalent post-transition metal and one of the pnictogens with chemical properties resembling its lighter group 15 siblings arsenic and antimony. Elemental bismuth may occur naturally, although its sulfide and oxide form important commercial ores. The free element is 86% as dense as lead. It is a brittle metal with a silvery white color when freshly produced, but surface oxidation can give it an iridescent tinge in numerous colours."],
    ["Polonium", 84, "Po", 208.982, "A rare and highly radioactive metal with no stable isotopes, polonium is chemically similar to selenium and tellurium, though its metallic character resembles that of its horizontal neighbors in the periodic table: thallium, lead, and bismuth. Due to the short half-life of all its isotopes, its natural occurrence is limited to tiny traces of the fleeting polonium-210 (with a half-life of 138 days) in uranium ores, as it is the penultimate daughter of natural uranium-238. Though slightly longer-lived isotopes exist, they are much more difficult to produce."],
    ["Astatine", 85, "At", 209.987, "Astatine is the rarest naturally occurring element in the Earth's crust, occurring only as the decay product of various heavier elements. All of astatine's isotopes are short-lived; the most stable is astatine-210, with a half-life of 8.1 hours. A sample of the pure element has never been assembled, because any macroscopic specimen would be immediately vaporized by the heat of its own radioactivity. The bulk properties of astatine are not known with certainty. It is likely to have a dark or lustrous appearance and may be a semiconductor or possibly a metal."],
    ["Radon", 86, "Rn", 222.018, "Radon is a radioactive, colorless, odorless, tasteless noble gas. It occurs naturally in minute quantities as an intermediate step in the normal radioactive decay chains through which thorium and uranium slowly decay into lead and various other short-lived radioactive elements. Radon itself is the immediate decay product of radium. Its most stable isotope, 222Rn, has a half-life of only 3.8 days, making it one of the rarest elements. It can also occur in some ground water like spring waters and hot springs."],
    ["Francium", 87, "Fr", 223.020, "Prior to Francium's discovery, it was referred to as eka-caesium. It is extremely radioactive; its most stable isotope, francium-223 (originally called actinium K after the natural decay chain it appears in), has a half-life of only 22 minutes. It is the second-most electropositive element, behind only caesium, and is the second rarest naturally occurring element (after astatine). The isotopes of francium decay quickly into astatine, radium, and radon."],
    ["Radium", 88, "Ra", 226.025, "Pure radium is silvery-white, but it readily reacts with nitrogen (rather than oxygen) on exposure to air, forming a black surface layer of radium nitride (Ra3N2). All isotopes of radium are highly radioactive, with the most stable isotope being radium-226, which has a half-life of 1600 years and decays into radon gas (specifically the isotope radon-222). When radium decays, ionizing radiation is a product, which can excite fluorescent chemicals and cause radioluminescence."],

    ["Actinium", 89, "Ac", 227.028, "Actinium was first isolated by French chemist André-Louis Debierne in 1899. Friedrich Oskar Giesel later independently isolated it in 1902 and, unaware that it was already known, gave it the name emanium. Actinium gave the name to the actinide series, a group of 15 similar elements between actinium and lawrencium in the periodic table. A soft, silvery-white radioactive metal, actinium reacts rapidly with oxygen and moisture in air forming a white coating of actinium oxide that prevents further oxidation."],
    ["Thorium", 90, "Th", 232.038, "Thorium is silvery and tarnishes black when it is exposed to air, forming thorium dioxide; it is moderately hard, malleable, and has a high melting point. Thorium is an electropositive actinide whose chemistry is dominated by the +4 oxidation state; it is quite reactive and can ignite in air when finely divided. All known thorium isotopes are unstable. The most stable isotope, 232Th, has a half-life of 14.05 billion years, or about the age of the universe; it decays very slowly via alpha decay, starting a decay chain named the thorium series that ends at stable 208Pb."],
    ["Protactinium", 91, "Pa", 231.036, "Protactinium is a dense, silvery-gray actinide metal which readily reacts with oxygen, water vapor and inorganic acids. It forms various chemical compounds in which protactinium is usually present in the oxidation state +5, but it can also assume +4 and even +3 or +2 states. Because of its scarcity, high radioactivity and high toxicity, there are currently no uses for protactinium outside scientific research, and for this purpose, protactinium is mostly extracted from spent nuclear fuel."],
    ["Uranium", 92, "U", 238.029, "Uranium is a silvery-grey metal in the actinide series of the periodic table. A uranium atom has 92 protons and 92 electrons, of which 6 are valence electrons. Uranium is weakly radioactive because all isotopes of uranium are unstable; the half-lives of its naturally occurring isotopes range between 159,200 years and 4.5 billion years. The most common isotopes in natural uranium are uranium-238 (which has 146 neutrons and accounts for over 99% of uranium on Earth) and uranium-235 (which has 143 neutrons)."],
    ["Neptunium", 93, "Np", 237.048, "A radioactive actinide metal, neptunium is the first transuranic element. Its position in the periodic table just after uranium, named after the planet Uranus, led to it being named after Neptune, the next planet beyond Uranus. A neptunium atom has 93 protons and 93 electrons, of which seven are valence electrons. Neptunium metal is silvery and tarnishes when exposed to air. The element occurs in three allotropic forms and it normally exhibits five oxidation states, ranging from +3 to +7."],
    ["Plutonium", 94, "Pu", 244.064, "Plutonium is an actinide metal of silvery-gray appearance that tarnishes when exposed to air, and forms a dull coating when oxidized. The element normally exhibits six allotropes and four oxidation states. It reacts with carbon, halogens, nitrogen, silicon, and hydrogen. When exposed to moist air, it forms oxides and hydrides that can expand the sample up to 70% in volume, which in turn flake off as a powder that is pyrophoric. It is radioactive and can accumulate in bones, which makes the handling of plutonium dangerous."],
    ["Americium", 95, "Am", 243.061, "Americium is a transuranic member of the actinide series, in the periodic table located under the lanthanide element europium, and thus by analogy was named after the Americas. Americium was first produced in 1944 by the group of Glenn T. Seaborg from Berkeley, California, at the Metallurgical Laboratory of the University of Chicago, a part of the Manhattan Project. Most americium is produced by uranium or plutonium being bombarded with neutrons in nuclear reactors – one tonne of spent nuclear fuel contains about 100 grams of americium."],
    ["Curium", 96, "Cm", 247.070, "Curium was first intentionally produced and identified in July 1944 by the group of Glenn T. Seaborg at the University of California, Berkeley. The discovery was kept secret and only released to the public in November 1947. Most curium is produced by bombarding uranium or plutonium with neutrons in nuclear reactors – one tonne of spent nuclear fuel contains about 20 grams of curium. It is a hard, dense, silvery metal with a relatively high melting point and boiling point for an actinide."],
    ["Berkelium", 97, "Bk", 247.070, "Beryllium is a member of the actinide and transuranium element series. It is named after the city of Berkeley, California, the location of the Lawrence Berkeley National Laboratory (then the University of California Radiation Laboratory) where it was discovered in December 1949. Berkelium was the fifth transuranium element discovered after neptunium, plutonium, curium and americium. It is a soft, silvery-white, radioactive metal."],
    ["Californium", 98, "Cf", 251.080, "Californium was first synthesized in 1950 at the Lawrence Berkeley National Laboratory (then the University of California Radiation Laboratory), by bombarding curium with alpha particles (helium-4 ions). It is an actinide element, the sixth transuranium element to be synthesized, and has the second-highest atomic mass of all the elements that have been produced in amounts large enough to see with the unaided eye (after einsteinium). The element was named after the university and the state of California."],
    ["Einsteinium", 99, "Es", "[254]", "Einsteinium was discovered as a component of the debris of the first hydrogen bomb explosion in 1952, and named after Albert Einstein. Its most common isotope einsteinium-253 (half-life 20.47 days) is produced artificially from decay of californium-253 in a few dedicated high-power nuclear reactors with a total yield on the order of one milligram per year. The reactor synthesis is followed by a complex process of separating einsteinium-253 from other actinides and products of their decay."],
    ["Fermium", 100, "Fm", 257.095, " It is an actinide and the heaviest element that can be formed by neutron bombardment of lighter elements, and hence the last element that can be prepared in macroscopic quantities, although pure fermium metal has not yet been prepared. A total of 19 isotopes are known, with 257Fm being the longest-lived with a half-life of 100.5 days. It was discovered in the debris of the first hydrogen bomb explosion in 1952, and named after Enrico Fermi, one of the pioneers of nuclear physics."],
    ["Mendelevium", 101, "Md", 258.1, "A metallic radioactive transuranic element in the actinide series, Mendelevium is the first element by atomic number that currently cannot be produced in macroscopic quantities through neutron bombardment of lighter elements. It is the third-to-last actinide and the ninth transuranic element. It can only be produced in particle accelerators by bombarding lighter elements with charged particles. A total of seventeen mendelevium isotopes are known, the most stable being 258Md with a half-life of 51 days."],
    ["Nobelium", 102, "No", 259.101, "Nobelium is named in honor of Alfred Nobel, the inventor of dynamite and benefactor of science. Like all elements with atomic number over 100, nobelium can only be produced in particle accelerators by bombarding lighter elements with charged particles. A total of twelve nobelium isotopes are known to exist; the most stable is 259No with a half-life of 58 minutes, but the shorter-lived 255No (half-life 3.1 minutes) is most commonly used in chemistry because it can be produced on a larger scale."],
    ["Lawrencium", 103, "Lr", "[262]", "Lawrencium is named in honor of Ernest Lawrence, inventor of the cyclotron, a device that was used to discover many artificial radioactive elements. A radioactive metal, lawrencium is the eleventh transuranic element and is also the final member of the actinide series. Like all elements with atomic number over 100, lawrencium can only be produced in particle accelerators by bombarding lighter elements with charged particles."],

    ["Rutherfordium", 104, "Rf", "[261]", "Rutherfordium is a synthetic chemical element, named after New Zealand physicist Ernest Rutherford. As a synthetic element, it is not found in nature and can only be created in a laboratory. It is radioactive; the most stable known isotope, 267Rf, has a half-life of approximately 1.3 hours. Chemistry experiments have confirmed that rutherfordium behaves as the heavier homologue to hafnium in group 4. The chemical properties of rutherfordium are characterized only partly."],
    ["Dubnium", 105, "Db", "[262]", "Dubnium is a synthetic chemical element. It is highly radioactive: the most stable known isotope, dubnium-268, has a half-life of about 28 hours. This greatly limits the extent of research on dubnium. Dubnium does not occur naturally on Earth and is produced artificially. The Soviet Joint Institute for Nuclear Research (JINR) claimed the first discovery of the element in 1968, followed by the American Lawrence Berkeley Laboratory in 1970."],
    ["Seaborgium", 106, "Sg", "[266]", "Seaborgium is a synthetic chemical element. It is named after the American nuclear chemist Glenn T. Seaborg. As a synthetic element, it can be created in a laboratory but is not found in nature. It is also radioactive; the most stable known isotope, 269Sg, has a half-life of approximately 14 minutes. Chemistry experiments have confirmed that seaborgium behaves as the heavier homologue to tungsten in group 6. The chemical properties of seaborgium are characterized only partly, but they compare well with the chemistry of the other group 6 elements."],
    ["Bohrium", 107, "Bh", "[264]", "Bohrium is a synthetic chemical element with the symbol Bh and atomic number 107. It is named after Danish physicist Niels Bohr. As a synthetic element, it can be created in a laboratory but is not found in nature. All known isotopes of bohrium are extremely radioactive; the most stable known isotope is 270Bh with a half-life of approximately 61 seconds, though the unconfirmed 278Bh may have a longer half-life of about 690 seconds. Chemistry experiments have confirmed that bohrium behaves as the heavier homologue to rhenium in group 7."],
    ["Hassium", 108, "Hs", "[269]", "Hassium is highly radioactive; its most stable known isotopes have half-lives of approximately ten seconds. One of its isotopes, 270Hs, has magic numbers of both protons and neutrons for deformed nuclei, which gives it greater stability against spontaneous fission. Hassium is a superheavy element; it has been produced in a laboratory only in very small quantities by fusing heavy nuclei with lighter ones. Natural occurrences of the element have been hypothesised, but none have ever been found."],
    ["Meitnerium", 109, "Mt", "[268]", "Meitnerium is a synthetic chemical element. It is an extremely radioactive synthetic element (an element not found in nature, but can be created in a laboratory). The most stable known isotope, meitnerium-278, has a half-life of 4.5 seconds, although the unconfirmed meitnerium-282 may have a longer half-life of 67 seconds. The GSI Helmholtz Centre for Heavy Ion Research near Darmstadt, Germany, first created this element in 1982. It is named after Lise Meitner."],
    ["Darmstadium", 110, "Ds", "[269]", "Darmstadium is an extremely radioactive synthetic element. The most stable known isotope, darmstadtium-281, has a half-life of approximately 12.7 seconds. Darmstadtium was first created in 1994 by the GSI Helmholtz Centre for Heavy Ion Research near the city of Darmstadt, Germany, after which it was named. Darmstadtium is calculated to have similar properties to its lighter homologues, nickel, palladium, and platinum."],
    ["Roentgenium", 111, "Rg", "[272]", "Roentgenium is an extremely radioactive synthetic element that can be created in a laboratory but is not found in nature. The most stable known isotope, roentgenium-282, has a half-life of 100 seconds, although the unconfirmed roentgenium-286 may have a longer half-life of about 10.7 minutes. Roentgenium was first created in 1994 by the GSI Helmholtz Centre for Heavy Ion Research near Darmstadt, Germany. It is named after the physicist Wilhelm Röntgen (also spelled Roentgen), who discovered X-rays."],
    ["Copernicium", 112, "Cn", "[277]", "Copernicium is a synthetic chemical element. Its known isotopes are extremely radioactive, and have only been created in a laboratory. The most stable known isotope, copernicium-285, has a half-life of approximately 28 seconds. Copernicium was first created in 1996 by the GSI Helmholtz Centre for Heavy Ion Research near Darmstadt, Germany. During reactions with gold, it has been shown to be an extremely volatile substance, so much so that it is possibly a gas or a volatile liquid at standard temperature and pressure."],
    ["Nihonium", 113, "Nh", "unknown", "Nihonium is a synthetic chemical element. It is extremely radioactive; its most stable known isotope, nihonium-286, has a half-life of about 10 seconds. Nihonium was first reported to have been created in 2003 by a Russian–American collaboration at the Joint Institute for Nuclear Research (JINR) in Dubna, Russia, and in 2004 by a team of Japanese scientists at Riken in Wakō, Japan. Very little is known about nihonium, as it has only been made in very small amounts that decay away within seconds."],
    ["Flerovium", 114, "Fl", "[289]", "Flerovium is a superheavy artificial chemical element. It is an extremely radioactive synthetic element. The element is named after the Flerov Laboratory of Nuclear Reactions of the Joint Institute for Nuclear Research in Dubna, Russia, where the element was discovered in 1998. The name of the laboratory, in turn, honours the Russian physicist Georgy Flyorov (Флёров in Cyrillic, hence the transliteration of 'yo' to 'e'). The name was adopted by IUPAC on 30 May 2012."],
    ["Moscovium", 115, "Mc", "unknown", "Moscovium is a synthetic chemical element with the symbol Mc and atomic number 115. It was first synthesized in 2003 by a joint team of Russian and American scientists at the Joint Institute for Nuclear Research (JINR) in Dubna, Russia. In December 2015, it was recognized as one of four new elements by the Joint Working Party of international scientific bodies IUPAC and IUPAP. On 28 November 2016, it was officially named after the Moscow Oblast, in which the JINR is situated."],
    ["Livermorium", 116, "Lv", "[298]", "Livermorium is a synthetic chemical element. It is an extremely radioactive element that has only been created in the laboratory and has not been observed in nature. The element is named after the Lawrence Livermore National Laboratory in the United States, which collaborated with the Joint Institute for Nuclear Research (JINR) in Dubna, Russia to discover livermorium during experiments made between 2000 and 2006."],
    ["Tenessine", 117, "Ts", "unknown", "Tennessine is a synthetic chemical element. It is the second-heaviest known element and the penultimate element of the 7th period of the periodic table. The discovery of tennessine was officially announced in Dubna, Russia, by a Russian–American collaboration in April 2010, which makes it the most recently discovered element as of 2020. One of its daughter isotopes was created directly in 2011, partially confirming the results of the experiment."],
    ["Oganesson", 118, "Og", "unknown", "Oganesson is a synthetic chemical element. It was first synthesized in 2002 at the Joint Institute for Nuclear Research (JINR) in Dubna, near Moscow, Russia, by a joint team of Russian and American scientists. In December 2015, it was recognized as one of four new elements by the Joint Working Party of the international scientific bodies IUPAC and IUPAP. It was formally named on 28 November 2016."]
];

var elementGroup = [
    ["Alkali Metal", "The alkali metals are all shiny, soft, highly reactive metals at standard temperature and pressure and readily lose their outermost electron to form cations with charge +1. They can all be cut easily with a knife due to their softness, exposing a shiny surface that tarnishes rapidly in air due to oxidation by atmospheric moisture and oxygen (and in the case of lithium, nitrogen). Because of their high reactivity, they must be stored under oil to prevent reaction with air, and are found naturally only in salts and never as the free elements."],
    ["Alkaline Earth", "The elements have very similar properties: they are all shiny, silvery-white, somewhat reactive metals at standard temperature and pressure. Structurally, they (together with helium) have in common an outer s-orbital which is full; that is, this orbital contains its full complement of two electrons, which the alkaline earth metals readily lose to form cations with charge +2, and an oxidation state of +2. All the discovered alkaline earth metals occur in nature, although radium occurs only through the decay chain of uranium and thorium and not as a primordial element."],
    ["Transition Metal", "Transition elements (also known as transition metals) are elements that have partially filled d orbitals. IUPAC defines transition elements as an element having a d subshell that is partially filled with electrons, or an element that has the ability to form stable cations with an incompletely filled d orbital. These elements have completely filled d orbitals in their ground states and even in some of their oxidation states. One such example is the +2 oxidation state of mercury, which corresponds to an electronic configuration of (n-1)d10."],
    ["Basic Metal", "Base metals are any nonferrous (they contain no iron) metals that are neither precious metals nor noble metals. Base metals are more common and more readily extracted than precious metals, which include gold, silver, platinum, and palladium. Noble metals, some of which also are precious, are unlike base metals because they resist oxidation. Pure base metals oxidize relatively easily. Except for copper, they all react with hydrochloric acid to form hydrogen gas. Base metals also are less expensive than their counterpart precious metals because they are so much more common."],
    ["Semi Metal", "Semimetals or metalloids are chemical elements that have properties of both metals and nonmetals. Metalloids are important semiconductors, often used in computers and other electronic devices. Semimetals or metalloids are found in a zig-zag line on the periodic table, separating the basic metals from the nonmetals. However, the defining characteristic of metalloids is not so much their position on the periodic table as the extremely small overlap between the bottom of the conduction band and top of the valence band."],
    ["Non Metal", "A nonmetal (or non-metal) is a chemical element that mostly lacks the characteristics of a metal. Physically, a nonmetal tends to have a relatively low melting point, boiling point, and density. A nonmetal is typically brittle when solid and usually has poor thermal conductivity and electrical conductivity. Chemically, nonmetals tend to have relatively high ionization energy, electron affinity, and electronegativity. They gain or share electrons when they react with other elements and chemical compounds."],
    ["Halogen", "The halogens are a group in the periodic table consisting of five chemically related elements. In the modern IUPAC nomenclature, this group is known as group 17. The name 'halogen' means 'salt-producing'. When halogens react with metals, they produce a wide range of salts, including calcium fluoride, sodium chloride, silver bromide and potassium iodide. The group of halogens is the only periodic table group that contains elements in three of the main states of matter at standard temperature and pressure."],
    ["Noble Gas", "The noble gases (historically also the inert gases; sometimes referred to as aerogens[1]) make up a class of chemical elements with similar properties; under standard conditions, they are all odorless, colorless, monatomic gases with very low chemical reactivity. For the first six periods of the periodic table, the noble gases are exactly the members of group 18. Noble gases are typically highly unreactive except when under particular extreme conditions. The inertness of noble gases makes them very suitable in applications where reactions are not wanted."],
    ["Lanthanide", "The lanthanide or lanthanoid series of chemical elements comprises the 15 metallic chemical elements. These elements, along with the chemically similar elements scandium and yttrium, are often collectively known as the rare earth elements. The informal chemical symbol Ln is used in general discussions of lanthanide chemistry to refer to any lanthanide. All lanthanide elements form trivalent cations, Ln3+, whose chemistry is largely determined by the ionic radius, which decreases steadily from lanthanum to lutetium."],
    ["Actinide", "The actinoid series encompasses the 15 metallic chemical elements with atomic numbers. The actinoid series derives its name from the first element in the series, actinium. The informal chemical symbol An is used in general discussions of actinoid chemistry to refer to any actinoid. The series mostly corresponds to the filling of the 5f electron shell, although actinium and thorium lack any 5f electrons, and curium and lawrencium have the same number as the preceding element. All actinides are radioactive and release energy upon radioactive decay."]
];

function tableInfo(i) {
    document.write("<sup>" + elements[i][1] + "</sup>" + elements[i][2] + "<h1>" + elements[i][0] + "</h1><h2>" + elements[i][3] + "</h2>");
}

function elementGrp(i) {
    document.write("<h1 class='group'>" + elementGroup[i][0] + "</h1>");
}

$(document).ready(function() {
    const TAB = "\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0";
    var info1 = $("#info1");
    var info2 = $("#info2");


    function info(id, i) {
        $(id).hover(function() {
            if (elements[i][3] == "unknown") {
                info1.text("Element Name: " + elements[i][0] + TAB + "Atomic Number: " + elements[i][1] + TAB + "Symbol: " + elements[i][2] + TAB + "Standard Atomic Weight: " + elements[i][3]);
                info2.text(elements[i][4]);
            } else {
                info1.text("Element Name: " + elements[i][0] + TAB + "Atomic Number: " + elements[i][1] + TAB + "Symbol: " + elements[i][2] + TAB + "Standard Atomic Weight: " + elements[i][3] + "u");
                info2.text(elements[i][4]);
            }
        });
    }

    for (var i = 0; i < 118; i++) {
        var id = "#" + elements[i][0].toLowerCase();
        info(id, i);
    }


    function elementGroupInfo(id, i) {
        $(id).hover(function() {
            info1.text("Element Group Name: " + elementGroup[i][0]);
            info2.text(elementGroup[i][1]);
        });
    }

    for (var i = 0; i < 10; i++) {
        var id = "#" + elementGroup[i][0].split(" ").join("").toLowerCase();
        elementGroupInfo(id, i);
    }
});